Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/routes.rb'
    - 'Gemfile'

Style/Documentation:
  Exclude:
    - 'app/*/*'
    - 'db/*/*'